# Training Setup

In [1]:
import numpy as np
import pandas as pd

In [2]:
RANDOM_STATE = 42
rng = np.random.default_rng(seed=RANDOM_STATE)

## 1 Train Test Split

### 1.1 Mathematical Notations

#### Dataset

##### Regression

$$
\large
D\,:=\,\biggl\{\bigl(X^{(i)},\,y^{(i)}\bigr)\;;\;X^{(i)}\in\mathbb{R}^d\;;\;y^{(i)}\in\mathbb{R}^1\biggr\}_{i=1}^n
$$

##### Binary Classification

$$
\large
D\,:=\,\biggl\{\bigl(X^{(i)},\,y^{(i)}\bigr)\;;\;X^{(i)}\in\mathbb{R}^d\;;\;y^{(i)}\in\bigl\{0,\,1\bigr\}\biggr\}_{i=1}^n
$$

##### Multi-class Classification

$$
\large
D\,:=\,\biggl\{\bigl(X^{(i)},\,y^{(i)}\bigr)\;;\;X^{(i)}\in\mathbb{R}^d\;;\;y^{(i)}\in\bigl\{1,\,2,\,3\bigr\}\biggr\}_{i=1}^n
$$

#### Features

$$
\large
\begin{aligned}
& X       && \text{Features matrix (Dataset)} \\[5pt]
& X^{(i)} && i^{\text{th}}\;\text{data-point (row in the dataset)} \\[5pt]
& X_i     && i^{\text{th}}\;\text{feature vector in matrix (column in the dataset)} \\[5pt]
& x_i     && i^{\text{th}}\;\text{value in feature vector}
\end{aligned}
$$

#### Target

$$
\large
\begin{aligned}
& y^{(i)}       && i^{\text{th}}\;\text{actual target value} \\[5pt]
& \hat{y}^{(i)} && i^{\text{th}}\;\text{predicted target value}
\end{aligned}
$$

### 1.2 Train and Test Dataset

#### Need for Train Test Split

Unbiased validation/testing of model on unseen data.

#### How Train/Test split works?

2. **Data preprocessing** is performed on Training set **after Train/Test split** to avoid **Data Leakage**.
3. Test set is later transformed using the statistical parameters learned from Training set.

```
            Raw Dataset
                 ↓
          Train/Test Split
                 ↓
       ┌─────────┴─────────┐
       ↓                   ↓
  Training Set        Testing Set
       ↓                   │
  Fit Encoder              │
       ↓                   │
  Fit Scaler               │
       ↓                   ↓
Transform Train      Transform Test
       ↓                   ↓
       └─────────┬─────────┘
                 ↓
              ML Model
```

#### Split Strategy

- There are different split strategies opted depending on the size of the dataset. 
- For example some dataset split ratios after shuffling :
  - **80-20** - 80% Training set 20% Testing set
  - **70-30** - 70% Training set 30% Testing set

#### API

In [3]:
from sklearn.model_selection import train_test_split

## 2 Examples

### 2.1 Balanced Dataset

In [4]:
bal_df = pd.DataFrame(
    {
        "X": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "y": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
    }
)
bal_df

   X  y
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0
5  5  1
6  6  1
7  7  1
8  8  1
9  9  1

In [5]:
bal_df["y"].value_counts().sort_index(ascending=False)

y
1    5
0    5
Name: count, dtype: int64

In [6]:
target = "y"
X = bal_df.drop(columns=target)
y = bal_df[target]

#### Example #1: Without Shuffling

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    shuffle=False,
    random_state=RANDOM_STATE,
)

##### Train set

In [8]:
X_train.shape, y_train.shape

((7, 1), (7,))

In [9]:
X_train.values

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
y_train.values

array([0, 0, 0, 0, 0, 1, 1])

##### Test set

In [11]:
X_test.shape, y_test.shape

((3, 1), (3,))

In [12]:
X_test.values

array([[7],
       [8],
       [9]])

In [13]:
y_test.values

array([1, 1, 1])

#### Example #2: Shuffle (default True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

##### Train set

In [15]:
X_train.values

array([[0],
       [7],
       [2],
       [9],
       [4],
       [3],
       [6]])

In [16]:
y_train.values

array([0, 1, 0, 1, 0, 0, 1])

##### Test set

In [17]:
X_test.values

array([[8],
       [1],
       [5]])

In [18]:
y_test.values

array([1, 0, 1])

### 2.2 Imbalanced Dataset

In [19]:
imb_df = pd.DataFrame(
    {
        "X": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "y": [1, 0, 0, 1, 1, 1, 1, 1, 0, 1],
    }
)
imb_df

   X  y
0  0  1
1  1  0
2  2  0
3  3  1
4  4  1
5  5  1
6  6  1
7  7  1
8  8  0
9  9  1

In [20]:
imb_df["y"].value_counts().sort_index(ascending=False)

y
1    7
0    3
Name: count, dtype: int64

In [21]:
target = "y"
X = imb_df.drop(columns=target)
y = imb_df[target]

#### Example #1: Unstratified sampling

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=RANDOM_STATE)

##### Train set

In [23]:
y_train.value_counts().sort_index(ascending=False)

y
1    6
0    1
Name: count, dtype: int64

##### Test set

In [24]:
y_test.value_counts().sort_index(ascending=False)

y
1    1
0    2
Name: count, dtype: int64

#### Example #2: Stratified sampling

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    stratify=y,
    random_state=RANDOM_STATE,
)

##### Train set

In [26]:
y_train.value_counts().sort_index(ascending=False)

y
1    5
0    2
Name: count, dtype: int64

##### Test set

In [27]:
y_test.value_counts().sort_index(ascending=False)

y
1    2
0    1
Name: count, dtype: int64